Class {
	#name : #DvtDataTableDictOfListsProcessor,
	#superclass : #DvtDataTableProcessor,
	#category : #'DataVisualizationTool-Boundary'
}

{ #category : #private }
DvtDataTableDictOfListsProcessor >> apply [
	
]

{ #category : #api }
DvtDataTableDictOfListsProcessor >> putCellValue: newValue at: coord [
	
]

{ #category : #api }
DvtDataTableDictOfListsProcessor >> removeCellValueAt: coord [
	
]
