Class {
	#name : #DvtDataTableListOfDictsProcessor,
	#superclass : #DvtDataTableProcessor,
	#category : #'DataVisualizationTool-Boundary'
}

{ #category : #private }
DvtDataTableListOfDictsProcessor >> apply [
	
]

{ #category : #api }
DvtDataTableListOfDictsProcessor >> putCellValue: newValue at: coord [
	
]

{ #category : #api }
DvtDataTableListOfDictsProcessor >> removeCellValueAt: coord [
	
]
