Class {
	#name : #DvtVisualizerPresenter,
	#superclass : #DvtPresenter,
	#category : #'DataVisualizationTool-Boundary'
}

{ #category : #specs }
DvtVisualizerPresenter class >> defaultSpec [
	^ SpecLayout composed newColumn: [ :column |
		
	]
]

{ #category : #initialization }
DvtVisualizerPresenter >> initializePresenter [
	super initializePresenter.
	
]

{ #category : #initialization }
DvtVisualizerPresenter >> initializeWidgets [
	
]
